# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeyfertConfigGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeyfertConfigGUI(object):
    def setupUi(self, SeyfertConfigGUI):
        SeyfertConfigGUI.setObjectName("SeyfertConfigGUI")
        SeyfertConfigGUI.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(SeyfertConfigGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Optima")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.f_sky = QtWidgets.QLineEdit(self.centralwidget)
        self.f_sky.setGeometry(QtCore.QRect(130, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Optima")
        self.f_sky.setFont(font)
        self.f_sky.setObjectName("f_sky")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 60, 16))
        self.label_3.setObjectName("label_3")
        self.stem_disps = QtWidgets.QTableWidget(self.centralwidget)
        self.stem_disps.setGeometry(QtCore.QRect(620, 130, 111, 231))
        self.stem_disps.setObjectName("stem_disps")
        self.stem_disps.setColumnCount(1)
        self.stem_disps.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stem_disps.setItem(6, 0, item)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(620, 110, 131, 16))
        self.label_8.setObjectName("label_8")
        self.cosmo_pars = QtWidgets.QTableWidget(self.centralwidget)
        self.cosmo_pars.setGeometry(QtCore.QRect(800, 130, 451, 261))
        self.cosmo_pars.setMinimumSize(QtCore.QSize(441, 0))
        self.cosmo_pars.setStyleSheet("")
        self.cosmo_pars.setObjectName("cosmo_pars")
        self.cosmo_pars.setColumnCount(5)
        self.cosmo_pars.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cosmo_pars.setItem(8, 4, item)
        self.cosmo_pars.horizontalHeader().setDefaultSectionSize(70)
        self.cosmo_pars.verticalHeader().setDefaultSectionSize(25)
        self.cosmo_pars.verticalHeader().setMinimumSectionSize(10)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(800, 110, 161, 16))
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 208, 33))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cosmo_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.cosmo_label.setObjectName("cosmo_label")
        self.horizontalLayout.addWidget(self.cosmo_label)
        self.cosmological_model = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cosmological_model.setObjectName("cosmological_model")
        self.cosmological_model.addItem("")
        self.horizontalLayout.addWidget(self.cosmological_model)
        self.is_universe_flat = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.is_universe_flat.setEnabled(True)
        self.is_universe_flat.setChecked(True)
        self.is_universe_flat.setTristate(False)
        self.is_universe_flat.setObjectName("is_universe_flat")
        self.horizontalLayout.addWidget(self.is_universe_flat)
        self.probes = QtWidgets.QTabWidget(self.centralwidget)
        self.probes.setGeometry(QtCore.QRect(10, 120, 591, 481))
        self.probes.setWhatsThis("")
        self.probes.setObjectName("probes")
        self.Lensing = QtWidgets.QWidget()
        self.Lensing.setObjectName("Lensing")
        self.ell_widget = QtWidgets.QWidget(self.Lensing)
        self.ell_widget.setGeometry(QtCore.QRect(10, 30, 431, 151))
        self.ell_widget.setObjectName("ell_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.ell_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 124))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ell_log_number = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.ell_log_number.setEnabled(True)
        self.ell_log_number.setMinimum(20)
        self.ell_log_number.setMaximum(200)
        self.ell_log_number.setProperty("value", 100)
        self.ell_log_number.setObjectName("ell_log_number")
        self.gridLayout_3.addWidget(self.ell_log_number, 3, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 3, 0, 1, 1)
        self.minMultipoleLabel_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.minMultipoleLabel_4.setObjectName("minMultipoleLabel_4")
        self.gridLayout_3.addWidget(self.minMultipoleLabel_4, 0, 0, 1, 1)
        self.ell_log_selection = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ell_log_selection.setChecked(False)
        self.ell_log_selection.setObjectName("ell_log_selection")
        self.gridLayout_3.addWidget(self.ell_log_selection, 2, 0, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_6.setMinimum(0.0)
        self.doubleSpinBox_6.setMaximum(5000.0)
        self.doubleSpinBox_6.setSingleStep(0.1)
        self.doubleSpinBox_6.setProperty("value", 5000.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_3.addWidget(self.doubleSpinBox_6, 1, 1, 1, 1)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_14.setMinimum(0.0)
        self.doubleSpinBox_14.setMaximum(5000.0)
        self.doubleSpinBox_14.setSingleStep(0.1)
        self.doubleSpinBox_14.setProperty("value", 10.0)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout_3.addWidget(self.doubleSpinBox_14, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.Lensing)
        self.widget.setGeometry(QtCore.QRect(10, 180, 571, 51))
        self.widget.setObjectName("widget")
        self.external_ell_box = QtWidgets.QCheckBox(self.widget)
        self.external_ell_box.setGeometry(QtCore.QRect(0, 20, 161, 20))
        self.external_ell_box.setChecked(True)
        self.external_ell_box.setObjectName("external_ell_box")
        self.external_ell_filename = QtWidgets.QLineEdit(self.widget)
        self.external_ell_filename.setGeometry(QtCore.QRect(160, 20, 401, 21))
        self.external_ell_filename.setObjectName("external_ell_filename")
        self.is_void_present = QtWidgets.QCheckBox(self.Lensing)
        self.is_void_present.setGeometry(QtCore.QRect(0, 10, 341, 20))
        self.is_void_present.setChecked(True)
        self.is_void_present.setObjectName("is_void_present")
        self.widget_2 = QtWidgets.QWidget(self.Lensing)
        self.widget_2.setGeometry(QtCore.QRect(10, 230, 391, 51))
        self.widget_2.setObjectName("widget_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 20, 271, 21))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_6.setObjectName("label_6")
        self.widget_12 = QtWidgets.QWidget(self.Lensing)
        self.widget_12.setGeometry(QtCore.QRect(20, 299, 541, 161))
        self.widget_12.setObjectName("widget_12")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.widget_12)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 521, 141))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 4, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.probes.addTab(self.Lensing, "")
        self.Void = QtWidgets.QWidget()
        self.Void.setObjectName("Void")
        self.gridWidget_2 = QtWidgets.QWidget(self.Void)
        self.gridWidget_2.setGeometry(QtCore.QRect(10, 290, 541, 131))
        self.gridWidget_2.setObjectName("gridWidget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridWidget_2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_70 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_70.setObjectName("label_70")
        self.gridLayout_11.addWidget(self.label_70, 0, 0, 1, 1)
        self.void_k_cut = QtWidgets.QDoubleSpinBox(self.gridWidget_2)
        self.void_k_cut.setDecimals(3)
        self.void_k_cut.setMaximum(96.99)
        self.void_k_cut.setSingleStep(0.001)
        self.void_k_cut.setProperty("value", 0.35)
        self.void_k_cut.setObjectName("void_k_cut")
        self.gridLayout_11.addWidget(self.void_k_cut, 2, 1, 1, 1)
        self.void_bias_file_5 = QtWidgets.QLineEdit(self.gridWidget_2)
        self.void_bias_file_5.setInputMask("")
        self.void_bias_file_5.setPlaceholderText("")
        self.void_bias_file_5.setObjectName("void_bias_file_5")
        self.gridLayout_11.addWidget(self.void_bias_file_5, 0, 1, 1, 1)
        self.void_marg_bias_5 = QtWidgets.QCheckBox(self.gridWidget_2)
        self.void_marg_bias_5.setObjectName("void_marg_bias_5")
        self.gridLayout_11.addWidget(self.void_marg_bias_5, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 3, 0, 1, 1)
        self.void_k_cut_width = QtWidgets.QDoubleSpinBox(self.gridWidget_2)
        self.void_k_cut_width.setDecimals(3)
        self.void_k_cut_width.setSingleStep(0.001)
        self.void_k_cut_width.setProperty("value", 0.1)
        self.void_k_cut_width.setObjectName("void_k_cut_width")
        self.gridLayout_11.addWidget(self.void_k_cut_width, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget_2)
        self.label_4.setWhatsThis("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 2, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.Void)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 551, 291))
        self.widget_5.setObjectName("widget_5")
        self.ell_widget_2 = QtWidgets.QWidget(self.widget_5)
        self.ell_widget_2.setGeometry(QtCore.QRect(10, 30, 431, 151))
        self.ell_widget_2.setObjectName("ell_widget_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.ell_widget_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 401, 124))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ell_log_number_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.ell_log_number_2.setEnabled(True)
        self.ell_log_number_2.setMinimum(20)
        self.ell_log_number_2.setMaximum(200)
        self.ell_log_number_2.setProperty("value", 100)
        self.ell_log_number_2.setObjectName("ell_log_number_2")
        self.gridLayout_4.addWidget(self.ell_log_number_2, 3, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_4.addWidget(self.label_56, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 3, 0, 1, 1)
        self.minMultipoleLabel_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.minMultipoleLabel_5.setObjectName("minMultipoleLabel_5")
        self.gridLayout_4.addWidget(self.minMultipoleLabel_5, 0, 0, 1, 1)
        self.ell_log_selection_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.ell_log_selection_2.setChecked(False)
        self.ell_log_selection_2.setObjectName("ell_log_selection_2")
        self.gridLayout_4.addWidget(self.ell_log_selection_2, 2, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_7.setMinimum(750.0)
        self.doubleSpinBox_7.setMaximum(1500.0)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setProperty("value", 1500.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_4.addWidget(self.doubleSpinBox_7, 1, 1, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_13.setMinimum(0.0)
        self.doubleSpinBox_13.setMaximum(100.0)
        self.doubleSpinBox_13.setSingleStep(0.1)
        self.doubleSpinBox_13.setProperty("value", 10.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_4.addWidget(self.doubleSpinBox_13, 0, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setGeometry(QtCore.QRect(10, 230, 391, 51))
        self.widget_4.setObjectName("widget_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 20, 271, 21))
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_7.setObjectName("label_7")
        self.is_void_present_2 = QtWidgets.QCheckBox(self.widget_5)
        self.is_void_present_2.setGeometry(QtCore.QRect(0, 10, 341, 20))
        self.is_void_present_2.setObjectName("is_void_present_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setGeometry(QtCore.QRect(10, 180, 391, 51))
        self.widget_3.setObjectName("widget_3")
        self.external_ell_box_2 = QtWidgets.QCheckBox(self.widget_3)
        self.external_ell_box_2.setGeometry(QtCore.QRect(0, 20, 161, 20))
        self.external_ell_box_2.setObjectName("external_ell_box_2")
        self.external_ell_filename_2 = QtWidgets.QLineEdit(self.widget_3)
        self.external_ell_filename_2.setGeometry(QtCore.QRect(160, 20, 221, 21))
        self.external_ell_filename_2.setObjectName("external_ell_filename_2")
        self.probes.addTab(self.Void, "")
        self.GCph = QtWidgets.QWidget()
        self.GCph.setObjectName("GCph")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.GCph)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 290, 541, 85))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.void_bias_file_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.void_bias_file_6.setInputMask("")
        self.void_bias_file_6.setPlaceholderText("")
        self.void_bias_file_6.setObjectName("void_bias_file_6")
        self.gridLayout_12.addWidget(self.void_bias_file_6, 0, 1, 1, 1)
        self.void_marg_bias_6 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.void_marg_bias_6.setChecked(True)
        self.void_marg_bias_6.setObjectName("void_marg_bias_6")
        self.gridLayout_12.addWidget(self.void_marg_bias_6, 1, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_74.setObjectName("label_74")
        self.gridLayout_12.addWidget(self.label_74, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_12.addWidget(self.comboBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 2, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.GCph)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 551, 291))
        self.widget_6.setObjectName("widget_6")
        self.ell_widget_3 = QtWidgets.QWidget(self.widget_6)
        self.ell_widget_3.setGeometry(QtCore.QRect(10, 30, 431, 151))
        self.ell_widget_3.setObjectName("ell_widget_3")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.ell_widget_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 401, 124))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ell_log_number_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.ell_log_number_3.setEnabled(True)
        self.ell_log_number_3.setMinimum(20)
        self.ell_log_number_3.setMaximum(200)
        self.ell_log_number_3.setProperty("value", 100)
        self.ell_log_number_3.setObjectName("ell_log_number_3")
        self.gridLayout_5.addWidget(self.ell_log_number_3, 3, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_57.setObjectName("label_57")
        self.gridLayout_5.addWidget(self.label_57, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 3, 0, 1, 1)
        self.minMultipoleLabel_6 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.minMultipoleLabel_6.setObjectName("minMultipoleLabel_6")
        self.gridLayout_5.addWidget(self.minMultipoleLabel_6, 0, 0, 1, 1)
        self.ell_log_selection_3 = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.ell_log_selection_3.setChecked(True)
        self.ell_log_selection_3.setObjectName("ell_log_selection_3")
        self.gridLayout_5.addWidget(self.ell_log_selection_3, 2, 0, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.doubleSpinBox_10.setMinimum(0.0)
        self.doubleSpinBox_10.setMaximum(100.0)
        self.doubleSpinBox_10.setSingleStep(0.1)
        self.doubleSpinBox_10.setProperty("value", 10.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_5.addWidget(self.doubleSpinBox_10, 0, 1, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.doubleSpinBox_9.setMinimum(750.0)
        self.doubleSpinBox_9.setMaximum(5000.0)
        self.doubleSpinBox_9.setSingleStep(0.1)
        self.doubleSpinBox_9.setProperty("value", 3000.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_5.addWidget(self.doubleSpinBox_9, 1, 1, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setGeometry(QtCore.QRect(10, 230, 391, 51))
        self.widget_7.setObjectName("widget_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 20, 271, 21))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_10.setObjectName("label_10")
        self.is_void_present_6 = QtWidgets.QCheckBox(self.widget_6)
        self.is_void_present_6.setGeometry(QtCore.QRect(0, 10, 341, 20))
        self.is_void_present_6.setChecked(True)
        self.is_void_present_6.setObjectName("is_void_present_6")
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setGeometry(QtCore.QRect(10, 180, 391, 51))
        self.widget_8.setObjectName("widget_8")
        self.external_ell_box_3 = QtWidgets.QCheckBox(self.widget_8)
        self.external_ell_box_3.setGeometry(QtCore.QRect(0, 20, 161, 20))
        self.external_ell_box_3.setObjectName("external_ell_box_3")
        self.external_ell_filename_3 = QtWidgets.QLineEdit(self.widget_8)
        self.external_ell_filename_3.setGeometry(QtCore.QRect(160, 20, 221, 21))
        self.external_ell_filename_3.setObjectName("external_ell_filename_3")
        self.probes.addTab(self.GCph, "")
        self.GCsp = QtWidgets.QWidget()
        self.GCsp.setObjectName("GCsp")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.GCsp)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 290, 541, 121))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_78.setObjectName("label_78")
        self.gridLayout_13.addWidget(self.label_78, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit.setInputMask("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_13.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.void_marg_bias_7 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.void_marg_bias_7.setChecked(True)
        self.void_marg_bias_7.setObjectName("void_marg_bias_7")
        self.gridLayout_13.addWidget(self.void_marg_bias_7, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_13.addWidget(self.checkBox, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 3, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_2, 3, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.GCsp)
        self.widget_9.setGeometry(QtCore.QRect(0, 0, 551, 291))
        self.widget_9.setObjectName("widget_9")
        self.ell_widget_4 = QtWidgets.QWidget(self.widget_9)
        self.ell_widget_4.setGeometry(QtCore.QRect(10, 30, 431, 151))
        self.ell_widget_4.setObjectName("ell_widget_4")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.ell_widget_4)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 401, 124))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ell_log_number_4 = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.ell_log_number_4.setEnabled(True)
        self.ell_log_number_4.setMinimum(20)
        self.ell_log_number_4.setMaximum(200)
        self.ell_log_number_4.setProperty("value", 100)
        self.ell_log_number_4.setObjectName("ell_log_number_4")
        self.gridLayout_6.addWidget(self.ell_log_number_4, 3, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 3, 0, 1, 1)
        self.minMultipoleLabel_7 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.minMultipoleLabel_7.setObjectName("minMultipoleLabel_7")
        self.gridLayout_6.addWidget(self.minMultipoleLabel_7, 0, 0, 1, 1)
        self.ell_log_selection_4 = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.ell_log_selection_4.setEnabled(True)
        self.ell_log_selection_4.setChecked(True)
        self.ell_log_selection_4.setObjectName("ell_log_selection_4")
        self.gridLayout_6.addWidget(self.ell_log_selection_4, 2, 0, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.doubleSpinBox_11.setMinimum(750.0)
        self.doubleSpinBox_11.setMaximum(5000.0)
        self.doubleSpinBox_11.setSingleStep(0.1)
        self.doubleSpinBox_11.setProperty("value", 3000.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_6.addWidget(self.doubleSpinBox_11, 1, 1, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_6)
        self.doubleSpinBox_12.setMinimum(0.0)
        self.doubleSpinBox_12.setMaximum(100.0)
        self.doubleSpinBox_12.setSingleStep(0.1)
        self.doubleSpinBox_12.setProperty("value", 10.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_6.addWidget(self.doubleSpinBox_12, 0, 1, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setGeometry(QtCore.QRect(10, 230, 411, 51))
        self.widget_10.setObjectName("widget_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 20, 291, 21))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setPlaceholderText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.widget_10)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_11.setObjectName("label_11")
        self.is_void_present_7 = QtWidgets.QCheckBox(self.widget_9)
        self.is_void_present_7.setGeometry(QtCore.QRect(0, 10, 341, 20))
        self.is_void_present_7.setChecked(True)
        self.is_void_present_7.setObjectName("is_void_present_7")
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setGeometry(QtCore.QRect(10, 180, 411, 51))
        self.widget_11.setObjectName("widget_11")
        self.external_ell_box_4 = QtWidgets.QCheckBox(self.widget_11)
        self.external_ell_box_4.setGeometry(QtCore.QRect(0, 20, 161, 20))
        self.external_ell_box_4.setObjectName("external_ell_box_4")
        self.external_ell_filename_4 = QtWidgets.QLineEdit(self.widget_11)
        self.external_ell_filename_4.setGeometry(QtCore.QRect(160, 20, 221, 21))
        self.external_ell_filename_4.setObjectName("external_ell_filename_4")
        self.probes.addTab(self.GCsp, "")
        self.json_save_button = QtWidgets.QPushButton(self.centralwidget)
        self.json_save_button.setGeometry(QtCore.QRect(10, 610, 151, 32))
        self.json_save_button.setObjectName("json_save_button")
        SeyfertConfigGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SeyfertConfigGUI)
        self.statusbar.setObjectName("statusbar")
        SeyfertConfigGUI.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(SeyfertConfigGUI)
        self.toolBar.setObjectName("toolBar")
        SeyfertConfigGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(SeyfertConfigGUI)
        self.actionSave.setCheckable(True)
        self.actionSave.setObjectName("actionSave")

        self.retranslateUi(SeyfertConfigGUI)
        self.probes.setCurrentIndex(1)
        self.external_ell_box.toggled['bool'].connect(self.external_ell_filename.setEnabled)
        self.external_ell_box.toggled['bool'].connect(self.ell_widget.setDisabled)
        self.ell_log_selection.toggled['bool'].connect(self.ell_log_number.setEnabled)
        self.external_ell_box_2.toggled['bool'].connect(self.ell_widget_2.setDisabled)
        self.external_ell_box_2.toggled['bool'].connect(self.external_ell_filename_2.setEnabled)
        self.ell_log_selection_2.toggled['bool'].connect(self.ell_log_number_2.setEnabled)
        self.ell_log_selection_3.toggled['bool'].connect(self.ell_log_number_3.setEnabled)
        self.external_ell_box_3.toggled['bool'].connect(self.external_ell_filename_3.setEnabled)
        self.external_ell_box_3.toggled['bool'].connect(self.ell_widget_3.setDisabled)
        self.ell_log_selection_4.toggled['bool'].connect(self.ell_log_number_4.setEnabled)
        self.external_ell_box_4.toggled['bool'].connect(self.ell_widget_4.setDisabled)
        self.external_ell_box_4.toggled['bool'].connect(self.external_ell_filename_4.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SeyfertConfigGUI)

    def retranslateUi(self, SeyfertConfigGUI):
        _translate = QtCore.QCoreApplication.translate
        SeyfertConfigGUI.setWindowTitle(_translate("SeyfertConfigGUI", "Forecast Configuration"))
        self.label.setText(_translate("SeyfertConfigGUI", "Survey Sky Fraction"))
        self.f_sky.setText(_translate("SeyfertConfigGUI", "0.3636102608321519"))
        self.label_3.setText(_translate("SeyfertConfigGUI", "Probes"))
        item = self.stem_disps.verticalHeaderItem(0)
        item.setText(_translate("SeyfertConfigGUI", "1"))
        item = self.stem_disps.verticalHeaderItem(1)
        item.setText(_translate("SeyfertConfigGUI", "2"))
        item = self.stem_disps.verticalHeaderItem(2)
        item.setText(_translate("SeyfertConfigGUI", "3"))
        item = self.stem_disps.verticalHeaderItem(3)
        item.setText(_translate("SeyfertConfigGUI", "4"))
        item = self.stem_disps.verticalHeaderItem(4)
        item.setText(_translate("SeyfertConfigGUI", "5"))
        item = self.stem_disps.verticalHeaderItem(5)
        item.setText(_translate("SeyfertConfigGUI", "6"))
        item = self.stem_disps.verticalHeaderItem(6)
        item.setText(_translate("SeyfertConfigGUI", "7"))
        item = self.stem_disps.horizontalHeaderItem(0)
        item.setText(_translate("SeyfertConfigGUI", "Value"))
        __sortingEnabled = self.stem_disps.isSortingEnabled()
        self.stem_disps.setSortingEnabled(False)
        item = self.stem_disps.item(0, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.00625"))
        item = self.stem_disps.item(1, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.01250"))
        item = self.stem_disps.item(2, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.01875"))
        item = self.stem_disps.item(3, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.02500"))
        item = self.stem_disps.item(4, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.03750"))
        item = self.stem_disps.item(5, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.05000"))
        item = self.stem_disps.item(6, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.10000"))
        self.stem_disps.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("SeyfertConfigGUI", "SteM Displacements"))
        item = self.cosmo_pars.verticalHeaderItem(0)
        item.setText(_translate("SeyfertConfigGUI", "h"))
        item = self.cosmo_pars.verticalHeaderItem(1)
        item.setText(_translate("SeyfertConfigGUI", "w0"))
        item = self.cosmo_pars.verticalHeaderItem(2)
        item.setText(_translate("SeyfertConfigGUI", "wa"))
        item = self.cosmo_pars.verticalHeaderItem(3)
        item.setText(_translate("SeyfertConfigGUI", "OmDE"))
        item = self.cosmo_pars.verticalHeaderItem(4)
        item.setText(_translate("SeyfertConfigGUI", "Omm"))
        item = self.cosmo_pars.verticalHeaderItem(5)
        item.setText(_translate("SeyfertConfigGUI", "Omb"))
        item = self.cosmo_pars.verticalHeaderItem(6)
        item.setText(_translate("SeyfertConfigGUI", "ns"))
        item = self.cosmo_pars.verticalHeaderItem(7)
        item.setText(_translate("SeyfertConfigGUI", "sigma8"))
        item = self.cosmo_pars.verticalHeaderItem(8)
        item.setText(_translate("SeyfertConfigGUI", "mnu"))
        item = self.cosmo_pars.horizontalHeaderItem(0)
        item.setText(_translate("SeyfertConfigGUI", "Fiducial"))
        item = self.cosmo_pars.horizontalHeaderItem(1)
        item.setText(_translate("SeyfertConfigGUI", "IsFree"))
        item = self.cosmo_pars.horizontalHeaderItem(2)
        item.setText(_translate("SeyfertConfigGUI", "Units"))
        item = self.cosmo_pars.horizontalHeaderItem(3)
        item.setText(_translate("SeyfertConfigGUI", "SteMFactor"))
        item = self.cosmo_pars.horizontalHeaderItem(4)
        item.setText(_translate("SeyfertConfigGUI", "DerivativeMethod"))
        __sortingEnabled = self.cosmo_pars.isSortingEnabled()
        self.cosmo_pars.setSortingEnabled(False)
        item = self.cosmo_pars.item(0, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.67"))
        item = self.cosmo_pars.item(0, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(0, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(0, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(0, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(1, 0)
        item.setText(_translate("SeyfertConfigGUI", "-1.0"))
        item = self.cosmo_pars.item(1, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(1, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(1, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(1, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(2, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.0"))
        item = self.cosmo_pars.item(2, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(2, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(2, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(2, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(3, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.68"))
        item = self.cosmo_pars.item(3, 1)
        item.setText(_translate("SeyfertConfigGUI", "false"))
        item = self.cosmo_pars.item(3, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(3, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(3, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(4, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.32"))
        item = self.cosmo_pars.item(4, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(4, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(4, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(4, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(5, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.05"))
        item = self.cosmo_pars.item(5, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(5, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(5, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(5, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(6, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.96"))
        item = self.cosmo_pars.item(6, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(6, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(6, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(6, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(7, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.816"))
        item = self.cosmo_pars.item(7, 1)
        item.setText(_translate("SeyfertConfigGUI", "true"))
        item = self.cosmo_pars.item(7, 2)
        item.setText(_translate("SeyfertConfigGUI", "None"))
        item = self.cosmo_pars.item(7, 3)
        item.setText(_translate("SeyfertConfigGUI", "1.0"))
        item = self.cosmo_pars.item(7, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        item = self.cosmo_pars.item(8, 0)
        item.setText(_translate("SeyfertConfigGUI", "0.06"))
        item = self.cosmo_pars.item(8, 1)
        item.setText(_translate("SeyfertConfigGUI", "false"))
        item = self.cosmo_pars.item(8, 2)
        item.setText(_translate("SeyfertConfigGUI", "eV"))
        item = self.cosmo_pars.item(8, 3)
        item.setText(_translate("SeyfertConfigGUI", "7.0"))
        item = self.cosmo_pars.item(8, 4)
        item.setText(_translate("SeyfertConfigGUI", "SteM"))
        self.cosmo_pars.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("SeyfertConfigGUI", "Cosmological Parameters"))
        self.cosmo_label.setText(_translate("SeyfertConfigGUI", "Cosmology"))
        self.cosmological_model.setItemText(0, _translate("SeyfertConfigGUI", "CPL"))
        self.is_universe_flat.setText(_translate("SeyfertConfigGUI", "Flat"))
        self.Lensing.setWhatsThis(_translate("SeyfertConfigGUI", "probe"))
        self.ell_log_number.setWhatsThis(_translate("SeyfertConfigGUI", "log_l_number"))
        self.label_55.setText(_translate("SeyfertConfigGUI", "Max Multipole"))
        self.label_41.setText(_translate("SeyfertConfigGUI", "log multipoles number"))
        self.minMultipoleLabel_4.setText(_translate("SeyfertConfigGUI", "Min Multipole"))
        self.ell_log_selection.setWhatsThis(_translate("SeyfertConfigGUI", "ell_log_selection"))
        self.ell_log_selection.setText(_translate("SeyfertConfigGUI", "Logarithmic Selection"))
        self.doubleSpinBox_6.setWhatsThis(_translate("SeyfertConfigGUI", "l_max"))
        self.doubleSpinBox_14.setWhatsThis(_translate("SeyfertConfigGUI", "l_min"))
        self.external_ell_box.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_checkbox"))
        self.external_ell_box.setText(_translate("SeyfertConfigGUI", "ExternalMultipolesFile"))
        self.external_ell_filename.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_filename"))
        self.external_ell_filename.setText(_translate("SeyfertConfigGUI", "wl_optm_ells_10_3000_log_nell_100_and_3000_5000_lin.txt"))
        self.is_void_present.setWhatsThis(_translate("SeyfertConfigGUI", "presence_flag"))
        self.is_void_present.setText(_translate("SeyfertConfigGUI", "Present"))
        self.lineEdit_2.setWhatsThis(_translate("SeyfertConfigGUI", "density_file"))
        self.lineEdit_2.setText(_translate("SeyfertConfigGUI", "gcph_dndz_redbook.h5"))
        self.label_6.setText(_translate("SeyfertConfigGUI", "DensityFile"))
        self.label_13.setText(_translate("SeyfertConfigGUI", "aIA"))
        self.label_14.setText(_translate("SeyfertConfigGUI", "cIA"))
        self.lineEdit_6.setWhatsThis(_translate("SeyfertConfigGUI", "nuis_param_aIA"))
        self.lineEdit_6.setText(_translate("SeyfertConfigGUI", "1.72"))
        self.label_15.setText(_translate("SeyfertConfigGUI", "etaIA"))
        self.label_16.setText(_translate("SeyfertConfigGUI", "betaIA"))
        self.lineEdit_7.setWhatsThis(_translate("SeyfertConfigGUI", "nuis_param_cIA"))
        self.lineEdit_7.setText(_translate("SeyfertConfigGUI", "0.0134"))
        self.lineEdit_8.setWhatsThis(_translate("SeyfertConfigGUI", "nuis_param_etaIA"))
        self.lineEdit_8.setText(_translate("SeyfertConfigGUI", "-0.41"))
        self.lineEdit_9.setWhatsThis(_translate("SeyfertConfigGUI", "nuis_param_betaIA"))
        self.lineEdit_9.setText(_translate("SeyfertConfigGUI", "2.17"))
        self.checkBox_2.setWhatsThis(_translate("SeyfertConfigGUI", "include_IA"))
        self.checkBox_2.setText(_translate("SeyfertConfigGUI", "Include Intrinsic Alignment"))
        self.probes.setTabText(self.probes.indexOf(self.Lensing), _translate("SeyfertConfigGUI", "Lensing"))
        self.Void.setWhatsThis(_translate("SeyfertConfigGUI", "probe"))
        self.label_70.setText(_translate("SeyfertConfigGUI", "Bias input file"))
        self.void_k_cut.setWhatsThis(_translate("SeyfertConfigGUI", "void_kcut_invMpc"))
        self.void_bias_file_5.setWhatsThis(_translate("SeyfertConfigGUI", "bias_file"))
        self.void_bias_file_5.setText(_translate("SeyfertConfigGUI", "voids_bias_vdn.h5"))
        self.void_marg_bias_5.setWhatsThis(_translate("SeyfertConfigGUI", "marginalize_bias_flag"))
        self.void_marg_bias_5.setText(_translate("SeyfertConfigGUI", "Marginalize Over Bias"))
        self.label_5.setText(_translate("SeyfertConfigGUI", "PowerSpectrumKCutWidth"))
        self.void_k_cut_width.setWhatsThis(_translate("SeyfertConfigGUI", "void_kcut_width_invMpc"))
        self.label_4.setText(_translate("SeyfertConfigGUI", "PowerSpectrumKCut"))
        self.ell_log_number_2.setWhatsThis(_translate("SeyfertConfigGUI", "log_l_number"))
        self.label_56.setText(_translate("SeyfertConfigGUI", "Max Multipole"))
        self.label_42.setText(_translate("SeyfertConfigGUI", "log multipoles number"))
        self.minMultipoleLabel_5.setText(_translate("SeyfertConfigGUI", "Min Multipole"))
        self.ell_log_selection_2.setWhatsThis(_translate("SeyfertConfigGUI", "ell_log_selection"))
        self.ell_log_selection_2.setText(_translate("SeyfertConfigGUI", "Logarithmic Selection"))
        self.doubleSpinBox_7.setWhatsThis(_translate("SeyfertConfigGUI", "l_max"))
        self.doubleSpinBox_13.setWhatsThis(_translate("SeyfertConfigGUI", "l_min"))
        self.lineEdit_3.setWhatsThis(_translate("SeyfertConfigGUI", "density_file"))
        self.lineEdit_3.setText(_translate("SeyfertConfigGUI", "voids_dndz_flagship_old.h5"))
        self.label_7.setText(_translate("SeyfertConfigGUI", "DensityFile"))
        self.is_void_present_2.setWhatsThis(_translate("SeyfertConfigGUI", "presence_flag"))
        self.is_void_present_2.setText(_translate("SeyfertConfigGUI", "Present"))
        self.external_ell_box_2.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_checkbox"))
        self.external_ell_box_2.setText(_translate("SeyfertConfigGUI", "ExternalMultipolesFile"))
        self.external_ell_filename_2.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_filename"))
        self.probes.setTabText(self.probes.indexOf(self.Void), _translate("SeyfertConfigGUI", "Void"))
        self.GCph.setWhatsThis(_translate("SeyfertConfigGUI", "probe"))
        self.void_bias_file_6.setWhatsThis(_translate("SeyfertConfigGUI", "bias_file"))
        self.void_bias_file_6.setText(_translate("SeyfertConfigGUI", "gcph_bias_piecewise.h5"))
        self.void_marg_bias_6.setWhatsThis(_translate("SeyfertConfigGUI", "marginalize_bias_flag"))
        self.void_marg_bias_6.setText(_translate("SeyfertConfigGUI", "Marginalize Over Bias"))
        self.label_74.setText(_translate("SeyfertConfigGUI", "Bias input file"))
        self.comboBox.setWhatsThis(_translate("SeyfertConfigGUI", "bias_derivative_method"))
        self.comboBox.setItemText(0, _translate("SeyfertConfigGUI", "SteM"))
        self.comboBox.setItemText(1, _translate("SeyfertConfigGUI", "Analytic"))
        self.label_2.setText(_translate("SeyfertConfigGUI", "BiasDerivativeMethod"))
        self.ell_log_number_3.setWhatsThis(_translate("SeyfertConfigGUI", "log_l_number"))
        self.label_57.setText(_translate("SeyfertConfigGUI", "Max Multipole"))
        self.label_43.setText(_translate("SeyfertConfigGUI", "log multipoles number"))
        self.minMultipoleLabel_6.setText(_translate("SeyfertConfigGUI", "Min Multipole"))
        self.ell_log_selection_3.setWhatsThis(_translate("SeyfertConfigGUI", "ell_log_selection"))
        self.ell_log_selection_3.setText(_translate("SeyfertConfigGUI", "Logarithmic Selection"))
        self.doubleSpinBox_10.setWhatsThis(_translate("SeyfertConfigGUI", "l_min"))
        self.doubleSpinBox_9.setWhatsThis(_translate("SeyfertConfigGUI", "l_max"))
        self.lineEdit_4.setWhatsThis(_translate("SeyfertConfigGUI", "density_file"))
        self.lineEdit_4.setText(_translate("SeyfertConfigGUI", "gcph_dndz_redbook.h5"))
        self.label_10.setText(_translate("SeyfertConfigGUI", "DensityFile"))
        self.is_void_present_6.setWhatsThis(_translate("SeyfertConfigGUI", "presence_flag"))
        self.is_void_present_6.setText(_translate("SeyfertConfigGUI", "Present"))
        self.external_ell_box_3.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_checkbox"))
        self.external_ell_box_3.setText(_translate("SeyfertConfigGUI", "ExternalMultipolesFile"))
        self.external_ell_filename_3.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_filename"))
        self.probes.setTabText(self.probes.indexOf(self.GCph), _translate("SeyfertConfigGUI", "GCph"))
        self.GCsp.setWhatsThis(_translate("SeyfertConfigGUI", "probe"))
        self.label_78.setText(_translate("SeyfertConfigGUI", "Bias input file"))
        self.lineEdit.setWhatsThis(_translate("SeyfertConfigGUI", "bias_file"))
        self.lineEdit.setText(_translate("SeyfertConfigGUI", "gcsp_bias_piecewise_4_bins.h5"))
        self.void_marg_bias_7.setWhatsThis(_translate("SeyfertConfigGUI", "marginalize_bias_flag"))
        self.void_marg_bias_7.setText(_translate("SeyfertConfigGUI", "Marginalize Over Bias"))
        self.checkBox.setWhatsThis(_translate("SeyfertConfigGUI", "compute_gcsp_cl_offdiag"))
        self.checkBox.setText(_translate("SeyfertConfigGUI", "Compute Off Diagonal Cls"))
        self.label_12.setText(_translate("SeyfertConfigGUI", "BiasDerivativeMethod"))
        self.comboBox_2.setWhatsThis(_translate("SeyfertConfigGUI", "bias_derivative_method"))
        self.comboBox_2.setItemText(0, _translate("SeyfertConfigGUI", "SteM"))
        self.comboBox_2.setItemText(1, _translate("SeyfertConfigGUI", "Analytic"))
        self.ell_log_number_4.setWhatsThis(_translate("SeyfertConfigGUI", "log_l_number"))
        self.label_58.setText(_translate("SeyfertConfigGUI", "Max Multipole"))
        self.label_44.setText(_translate("SeyfertConfigGUI", "log multipoles number"))
        self.minMultipoleLabel_7.setText(_translate("SeyfertConfigGUI", "Min Multipole"))
        self.ell_log_selection_4.setWhatsThis(_translate("SeyfertConfigGUI", "ell_log_selection"))
        self.ell_log_selection_4.setText(_translate("SeyfertConfigGUI", "Logarithmic Selection"))
        self.doubleSpinBox_11.setWhatsThis(_translate("SeyfertConfigGUI", "l_max"))
        self.doubleSpinBox_12.setWhatsThis(_translate("SeyfertConfigGUI", "l_min"))
        self.lineEdit_5.setWhatsThis(_translate("SeyfertConfigGUI", "density_file"))
        self.lineEdit_5.setText(_translate("SeyfertConfigGUI", "gcsp_dndz_4_bins.h5"))
        self.label_11.setText(_translate("SeyfertConfigGUI", "DensityFile"))
        self.is_void_present_7.setWhatsThis(_translate("SeyfertConfigGUI", "presence_flag"))
        self.is_void_present_7.setText(_translate("SeyfertConfigGUI", "Present"))
        self.external_ell_box_4.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_checkbox"))
        self.external_ell_box_4.setText(_translate("SeyfertConfigGUI", "ExternalMultipolesFile"))
        self.external_ell_filename_4.setWhatsThis(_translate("SeyfertConfigGUI", "ell_external_filename"))
        self.probes.setTabText(self.probes.indexOf(self.GCsp), _translate("SeyfertConfigGUI", "GCsp"))
        self.json_save_button.setText(_translate("SeyfertConfigGUI", "Save to JSON"))
        self.toolBar.setWindowTitle(_translate("SeyfertConfigGUI", "toolBar"))
        self.actionSave.setText(_translate("SeyfertConfigGUI", "Save"))
        self.actionSave.setToolTip(_translate("SeyfertConfigGUI", "save and close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SeyfertConfigGUI = QtWidgets.QMainWindow()
    ui = Ui_SeyfertConfigGUI()
    ui.setupUi(SeyfertConfigGUI)
    SeyfertConfigGUI.show()
    sys.exit(app.exec_())

